### ISSUE TITLE
exposed password

### ISSUE THREAD

**Issue by xioustic** [DAVIDSystems/DoNotSleep#2]
you have an exposed password in your build process using the /p flag of signtool.exe

https://github.com/DAVIDSystems/DoNotSleep/commit/0f8a2409ea2a851a0d038cde67cd86000a62c19c#diff-50d7322608f05b311843704ba0e14972c51e9781ab20ba177c164cdc385317eb

**Comment by DAVIDSystems** [comment]
setup folder deleted, as it contains nothing which needs to be public
